#!/bin/bash
# For high value Bitcoin data, will create 3 backup locations with
# 3 locations needed to restore
# and 3 Good signatures to verify the download.
export BAILS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
$BAILS_DIR/bin/bails 2 4 3
