name: Lint CI
on:
  pull_request:
  push:
    branches: [ master ]
    paths:
      - b
      - local/bin/*
      - '**.py'
jobs:
  shell-lint:
    name: Check shell code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint with shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -e 2012 -e SC2046 -e SC2086 -e SC2164
        with:
          ignore_paths: |
            ./local/bin/bails-wallet
            ./local/bin/ibd-progress
            ./local/bin/backupd
  # python-lint:
  #   name: Check Python code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pylint
  #     - name: Lint with pylint
  #       run: pylint **/*.py
